/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const rememberThingsRememberThingsLazyImport = createFileRoute(
  '/(remember-things)/remember-things',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const rememberThingsRememberThingsLazyRoute =
  rememberThingsRememberThingsLazyImport
    .update({
      path: '/remember-things',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(remember-things)/remember-things.lazy').then(
        (d) => d.Route,
      ),
    )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(remember-things)/remember-things': {
      id: '/remember-things'
      path: '/remember-things'
      fullPath: '/remember-things'
      preLoaderRoute: typeof rememberThingsRememberThingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  rememberThingsRememberThingsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/remember-things"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/remember-things": {
      "filePath": "(remember-things)/remember-things.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
